#!/bin/bash

# Install git, java, golang
echo "Installing vim git, java, golang"
sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -

sudo apt-get update
sudo apt-get install -y vim git default-jdk golang google-chrome-stable

# Install Flat Theme
echo "Installing paper theme"
sudo add-apt-repository ppa:snwh/pulp
sudo apt-get update
sudo apt-get install paper-gtk-theme
sudo apt-get install paper-icon-theme
sudo apt-get install caffeine # Disables lock/screensaver while watching fullscreen
sudo apt-get install unity-tweak-tool

# Install Intellij Idea Ultimate
echo "Installing Intellij"
wget https://download.jetbrains.com/idea/ideaIU-2016.1.1.tar.gz
tar -xvf ideaIU-*.tar.gz
rm -f ideaIU-*.tar.gz
mv ideaIU-* .idea

# Install Docker
echo "Installing Docker"
wget -qO- https://get.docker.com/ | sh
sudo usermod -aG docker michael

# Install Android SDK
wget http://dl.google.com/android/android-sdk_r24.4.1-linux.tgz
tar -xvf android-sdk*.tgz
mv android-sdk*/android-sdk-linux .android
rm -rf android-sdk*.tgz android-sdk*


# Update Android SDK
./.android/tools/android list sdk
echo "Enter a comma separated list of packages"
read package
./.android/tools/android update sdk --no-ui --filter "$package"
